# Generated by Django 2.2.7 on 2020-07-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='ResponseQuestion',
        ),
    ]
