# Generated by Django 2.2.7 on 2020-07-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapi', '0002_auto_20200729_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=10),
        ),
    ]
