# Generated by Django 2.2.7 on 2020-07-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapi', '0003_auto_20200729_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lesson',
            name='sequence',
            field=models.IntegerField(default=1),
        ),
    ]
