# Generated by Django 2.2.7 on 2020-07-29 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseapi', '0005_auto_20200729_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsequestion',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapi.Question'),
        ),
    ]
