# Generated by Django 2.2.7 on 2020-07-29 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseapi', '0007_auto_20200729_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapi.Course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseapi.Users')),
            ],
        ),
    ]
